version = 1

[[annotations]]
path = "**"
precedence = "closest"
# Original code provided by Ontario at https://github.com/ongov/FireGUARD
SPDX-FileCopyrightText = [
  "2020 Queen's Printer for Ontario",
  "2021-2026 Government of Canada"
]
SPDX-License-Identifier = "AGPL-3.0-or-later"
